services:
  elasticsearch:
    image: elasticsearch:9.2.1
    container_name: es
    environment:
      discovery.type: single-node   #tek düğümlü küme
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"   #Java bellek ayarları
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"] #sağlık kontrolü
      interval: 10s # her 10 saniyede bir kontrol et
      timeout: 10s # zaman aşımı süresi
      retries: 3 # başarısız deneme sayısı
    networks:
      - elastic
  logstash:
    image: logstash:9.2.1
    container_name: log
    environment:
      discovery.seed_hosts: logstash #keşif ana bilgisayarları
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"  #Java bellek ayarları
    volumes:
      - ./logstash/pipeline/logstash-nginx.config:/usr/share/logstash/pipeline/logstash-nginx.config
      - ./logstash/nginx.log:/home/nginx.log
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - elastic
    command: logstash -f /usr/share/logstash/pipeline/logstash-nginx.config
  kibana:
    image: kibana:9.2.1
    container_name: kib
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic
networks:
  elastic:
    driver: bridge